name: CI/CD Pipeline # Name of your workflow

on:
  push:
    branches: [main] # Trigger the workflow on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Run the job on an Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Checkout your code

      - name: Login to Docker Hub
        uses: docker/login-action@v2 # Log in to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Use your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }} # Use your Docker Hub password

      - name: Build and push Docker image
        uses: docker/build-push-action@v3 # Build and push your Docker image
        with:
          context: . # Build context (current directory)
          push: true # Push the image to Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/my-web-app:latest # Tag the image with your username and app name
